title: flatMap(Oslo) 2019
email: flatmap@arktekk.no
description: > # flatMap(Oslo) 2019 functional programming conference
baseurl: ""
url: "http://2019.flatmap.no"

destination: docs
include: ["_pages"]
permalink: /:title/
exclude: [vendor]
includes:
  - _pages

collections:
  talks:
    output: true
    permalink: /:collection/:name

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
